export const DEFAULT_CLIENTS = [
  'Altessia',
  'Grupo Emeis',
  'isEazy',
  'Smoking',
  'BeeDigital',
  'Aresbank',
  'Halehou/Hipotecas Digitales',
  'IML',
  'Japemasa',
  'SIDN',
  'Deoleo',
  'Ecoembes',
  'iAhorro',
  'Realia',
  'Sportium',
  'The Valley',
  'Thielmann',
  'UGR',
  'Aedas',
  'Clece',
  'Faes Farma',
  'Fotocasa / Datavenues',
  'Hawha Energy (Imagina Energía y Quantica Renovables)',
  'Noelia Romero',
  'slot.com',
  'Vestige Colection',
  'Ortodoncis',
  'Kaname',
  'Pastor y Galvez',
  'PRIM',
  'Grupo Alhambra IT',
  'Papelmatic',
  'Dékuple',
  'Limepay',
  'Affidea',
  'Manuel Yebra',
  'Entradas Master',
  'Fluidra',
  'Colegios RC',
  'Consell de Mallorca',
  'Grupo Eulen',
  'Ohai Resorts',
  'UNIR - Contraste',
  'BCO Congresos',
  'Grupo Azkoyen',
  'ICDE',
  'Vector Solar',
  '3 Claveles',
  'Estabanell',
  'Hidráulicas Jaén',
  'IBP Tenis',
  'Patineteros',
  'Repsol',
  'Asisa',
  'De Hualdo',
  'Comparar y ahorrar',
  'Billin',
  'Grupo Apolo (Mariscos Apolo y Cocelang)',
  'Simetría Group',
  'Andamur',
  'CTT Express',
  'Diglo',
  'Divina Seguros',
  'Grupo Vértice',
  'Legend eBikes',
  'Sanferbike',
  'Sublima',
  'Tega',
  'Unilabs',
  'WTW (Willis Tower Watson)',
  'Nautichandler',
  'Mercurius Health',
  'Nearby Computing',
  'Cadpet',
]
